---
title: "07.hw"
output: html_document
date: "2025-05-13"
---

#1.What is your current grade in the class? How many issues are open in our research repository?
I have 75 points and 2 open issues. 
#2.Re-reading this week’s reading, what are 2 things that resonate with you now that made little practical sense in week 2. What is one aspect that you still wonder about or is unclear?
I now understand the primary output of mapping squence reads, SAM/BAM, and the information that can be used from these files. Another component I understand on the 2nd read more is the meaning of "contigs". I am still wondering about data visualixation, where/how it should be used in my pipeline of data analysis. 

#3.What is epigenetics and how could it relate to your own research project?
Mechanisms that cause modifications in without changing the genetic code. This could relate to my project, as I am wanting to see if gene expression in hatchery oysters is different from wildtype oysters. Epigenetic factors could cause differences in expression without altering the nucleotides between hatchery and wildtype.
#4.Describe what a GFF file is?
Genome feature formate, are files designed to hold annotations to genetic sequences. 
#5.What are two ways describing CG motifs could have value?
CG motifs are the primary target for DNA methylation, which is an epigenetic modification. Another reason describing CG motifs could have value is for epigenetic inheritance, to help understand how epigenetic information is inherited across generations.   